import '../styles/globals.css'
import { Providers } from "./provider";
import ContentPage from '../components/ContentPage'



export const metadata = {
  title: 'Chat GPT By Mai Tuan Sang',
  description: 'Generated by Mai Tuan Sang',
}

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode

}) {

  return (
    <html lang="en">
      <head />
      <meta name="viewport" content="width=device-width, initial-scale=1"></meta>
      <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/highlight.js/11.8.0/styles/atom-one-dark.min.css" />
      <body>
          <Providers>
              <ContentPage>
                {children}
              </ContentPage>
          </Providers>
      </body>
    </html>
  )
}
