import '../styles/globals.css'
import { Providers } from "./provider";
import ContentPage from '../components/ContentPage'


export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {

  return (
    <html lang="en">
      <head />
      <body>
       
          <Providers>
              <ContentPage>
                {children}
              </ContentPage>
          </Providers>
      </body>
    </html>
  )
}
