'use client'

import Head from 'next/head'
import ContentPage from '../components/ContentPage';
import Login from '../modules/Accounts/Login';
import { RootState } from '../store/store';
import { useSelector } from 'react-redux';

export default function LoginPage() {
  return (
    <>
      <Head>
        <title>Login</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Login/>
    </>
  )
}
